"""Build GibsGraph training pairs from Vestio's verified compliance data.

Converts Vestio's parsed EUR-Lex chunks + cross-reference graph into
supervised training pairs: (input_text, expected_graph).

The expected graph is verified ground truth — parsed from official EUR-Lex
sources by a human, not generated by an LLM. This avoids the "student
correcting own test" problem.

Training pair format (JSONL):
{
    "id": "ai_act_art6",
    "input_text": "Article 6 Classification rules for high-risk...",
    "metadata": {
        "regulation": "ai_act",
        "article_id": "Article 6",
        "chunk_type": "article",
        "source_celex": "32024R1689"
    },
    "expected_graph": {
        "source_node": {
            "id": "ai_act_art6",
            "label": "Article",
            "properties": {"regulation": "ai_act", "article_id": "Article 6", ...}
        },
        "target_nodes": [
            {"id": "ai_act_annex3", "label": "Annex", "properties": {...}},
            {"id": "gdpr_art6", "label": "Article", "properties": {...}},
            ...
        ],
        "edges": [
            {"source": "ai_act_art6", "target": "ai_act_annex3",
             "type": "REFERENCES", "weight": 0.8},
            {"source": "ai_act_art6", "target": "gdpr_art6",
             "type": "CROSS_REGULATES", "weight": 0.9},
            ...
        ]
    },
    "quality": {
        "has_cross_references": true,
        "cross_ref_count": 7,
        "edge_count": 11,
        "has_cross_regulation": true,
        "text_length": 4041,
        "verified_source": "eurlex_html"
    }
}

Usage:
    python data/scripts/build_training_pairs.py
    python data/scripts/build_training_pairs.py --min-edges 1 \
        --output data/training/eurlex_pairs.jsonl
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

VESTIO_ROOT = Path(os.environ.get("VESTIO_ROOT", "vestio"))
DEFAULT_OUTPUT = Path("data/training/eurlex_pairs.jsonl")

# Edge weight scheme (from Vestio's migrate_to_neo4j.py)
EDGE_WEIGHTS = {
    "AMENDS": 1.0,
    "SUPPLEMENTS": 0.95,
    "CROSS_REGULATES": 0.9,
    "IMPLIES": 0.85,
    "REFERENCES": 0.8,
    "DEFINES": 0.7,
    "INTERPRETS": 0.5,
    "CONTAINS": 0.3,
    "HAS_ARTICLE": 0.1,
}


def classify_chunk_id(chunk_id: str) -> str:
    """Determine Neo4j node label from chunk_id pattern."""
    if "_rec" in chunk_id and "_art" not in chunk_id:
        return "Recital"
    if "_annex" in chunk_id:
        return "Annex"
    if "_para" in chunk_id:
        return "Paragraph"
    if "_delegated" in chunk_id or "_rts_" in chunk_id or "_its_" in chunk_id:
        return "DelegatedAct"
    return "Article"


def detect_regulation(chunk_id: str) -> str:
    """Extract regulation name from chunk_id prefix."""
    if chunk_id.startswith("dora"):
        return "dora"
    if chunk_id.startswith("gdpr"):
        return "gdpr"
    return "ai_act"


def classify_edge(source_id: str, target_id: str) -> str:
    """Determine edge type based on source and target."""
    source_reg = detect_regulation(source_id)
    target_reg = detect_regulation(target_id)

    if source_reg != target_reg:
        return "CROSS_REGULATES"

    if classify_chunk_id(source_id) == "Recital" or classify_chunk_id(target_id) == "Recital":
        return "INTERPRETS"

    src_is_delegated = classify_chunk_id(source_id) == "DelegatedAct"
    tgt_is_delegated = classify_chunk_id(target_id) == "DelegatedAct"
    if src_is_delegated or tgt_is_delegated:
        return "SUPPLEMENTS"

    return "REFERENCES"


def build_node_props(chunk_id: str, chunk_map: dict[str, dict]) -> dict:
    """Build node properties from chunk metadata."""
    meta = chunk_map.get(chunk_id, {})
    return {
        "id": chunk_id,
        "label": classify_chunk_id(chunk_id),
        "properties": {
            "chunk_id": chunk_id,
            "regulation": detect_regulation(chunk_id),
            "article_id": meta.get("article_id", ""),
            "title": meta.get("title", ""),
            "chapter": meta.get("chapter", ""),
            "chunk_type": meta.get("chunk_type", ""),
            "binding": meta.get("binding", True),
        },
    }


def build_training_pairs(
    chunks: list[dict],
    graph: dict[str, dict],
    *,
    min_edges: int = 0,
    min_text_length: int = 50,
) -> list[dict]:
    """Convert Vestio data into GibsGraph training pairs."""
    chunk_map = {c["id"]: c for c in chunks}
    pairs = []

    for chunk in chunks:
        chunk_id = chunk["id"]
        text = chunk.get("text", "").strip()

        # Skip chunks that are too short
        if len(text) < min_text_length:
            continue

        # Get graph edges for this chunk
        node_data = graph.get(chunk_id, {})
        references = node_data.get("references", [])

        # Skip if below minimum edge count
        if len(references) < min_edges:
            continue

        # Build edges with types and weights
        edges = []
        target_nodes = []
        has_cross_reg = False

        for target_id in references:
            edge_type = classify_edge(chunk_id, target_id)
            weight = EDGE_WEIGHTS.get(edge_type, 0.8)
            edges.append({
                "source": chunk_id,
                "target": target_id,
                "type": edge_type,
                "weight": weight,
            })
            target_nodes.append(build_node_props(target_id, chunk_map))

            if edge_type == "CROSS_REGULATES":
                has_cross_reg = True

        # Also include reverse edges (referenced_by) as context
        referenced_by = node_data.get("referenced_by", [])
        reverse_edges = []
        for source_id in referenced_by:
            edge_type = classify_edge(source_id, chunk_id)
            reverse_edges.append({
                "source": source_id,
                "target": chunk_id,
                "type": edge_type,
                "weight": EDGE_WEIGHTS.get(edge_type, 0.8),
            })

        pair = {
            "id": chunk_id,
            "input_text": text,
            "metadata": {
                "regulation": chunk.get("regulation", ""),
                "article_id": chunk.get("article_id", ""),
                "chunk_type": chunk.get("chunk_type", ""),
                "chapter": chunk.get("chapter", ""),
                "title": chunk.get("title", ""),
                "source_celex": chunk.get("source_celex", chunk.get("document_id", "")),
                "effective_date": chunk.get("effective_date", ""),
                "cross_references_in_text": chunk.get("cross_references", []),
                "recital_ids": chunk.get("recital_ids", []),
            },
            "expected_graph": {
                "source_node": build_node_props(chunk_id, chunk_map),
                "target_nodes": target_nodes,
                "edges": edges,
                "reverse_edges": reverse_edges,
            },
            "quality": {
                "has_cross_references": len(chunk.get("cross_references", [])) > 0,
                "cross_ref_count": len(chunk.get("cross_references", [])),
                "edge_count": len(edges),
                "reverse_edge_count": len(reverse_edges),
                "has_cross_regulation": has_cross_reg,
                "text_length": len(text),
                "verified_source": "eurlex_html",
            },
        }
        pairs.append(pair)

    return pairs


def main() -> None:
    parser = argparse.ArgumentParser(description="Build training pairs from Vestio data")
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="Output JSONL file path",
    )
    parser.add_argument(
        "--min-edges", type=int, default=0,
        help="Minimum edges per chunk to include (0 = include all)",
    )
    parser.add_argument(
        "--min-text", type=int, default=50,
        help="Minimum text length to include",
    )
    parser.add_argument(
        "--stats-only", action="store_true",
        help="Print statistics without writing output",
    )
    parser.add_argument(
        "--vestio-root", type=Path, default=VESTIO_ROOT,
        help="Path to Vestio repository root (or set VESTIO_ROOT env var)",
    )
    args = parser.parse_args()

    # Load Vestio data
    vestio = args.vestio_root
    chunks_path = vestio / "data/parsed/chunks.json"
    graph_path = vestio / "data/parsed/cross_reference_graph.json"

    if not chunks_path.exists():
        print(f"ERROR: {chunks_path} not found.")
        print(f"Set VESTIO_ROOT env var or pass --vestio-root /path/to/vestio")
        raise SystemExit(1)

    print(f"Loading chunks from {chunks_path}...")
    with open(chunks_path, encoding="utf-8") as f:
        chunks = json.load(f)
    print(f"  {len(chunks)} chunks loaded")

    print(f"Loading graph from {graph_path}...")
    with open(graph_path, encoding="utf-8") as f:
        graph = json.load(f)
    print(f"  {len(graph)} graph nodes loaded")

    # Build pairs
    pairs = build_training_pairs(
        chunks, graph, min_edges=args.min_edges, min_text_length=args.min_text,
    )

    # Statistics
    total = len(pairs)
    with_edges = sum(1 for p in pairs if p["quality"]["edge_count"] > 0)
    with_cross_reg = sum(1 for p in pairs if p["quality"]["has_cross_regulation"])
    with_text_refs = sum(1 for p in pairs if p["quality"]["has_cross_references"])
    total_edges = sum(p["quality"]["edge_count"] for p in pairs)
    total_reverse = sum(p["quality"]["reverse_edge_count"] for p in pairs)

    by_regulation: dict[str, int] = {}
    by_type: dict[str, int] = {}
    by_edge_type: dict[str, int] = {}
    for p in pairs:
        reg = p["metadata"]["regulation"]
        by_regulation[reg] = by_regulation.get(reg, 0) + 1
        ct = p["metadata"]["chunk_type"]
        by_type[ct] = by_type.get(ct, 0) + 1
        for e in p["expected_graph"]["edges"]:
            et = e["type"]
            by_edge_type[et] = by_edge_type.get(et, 0) + 1

    text_lengths = [p["quality"]["text_length"] for p in pairs]
    avg_text = sum(text_lengths) / len(text_lengths) if text_lengths else 0

    print(f"\n{'=' * 60}")
    print("TRAINING PAIR STATISTICS")
    print(f"{'=' * 60}")
    print(f"  Total pairs:              {total}")
    print(f"  With graph edges:         {with_edges} ({with_edges * 100 // total}%)")
    print(f"  With cross-regulation:    {with_cross_reg}")
    print(f"  With text cross-refs:     {with_text_refs}")
    print(f"  Total forward edges:      {total_edges}")
    print(f"  Total reverse edges:      {total_reverse}")
    print(f"  Avg text length:          {avg_text:.0f} chars")
    print("\n  By regulation:")
    for reg, count in sorted(by_regulation.items()):
        print(f"    {reg}: {count}")
    print("\n  By chunk type:")
    for ct, count in sorted(by_type.items()):
        print(f"    {ct}: {count}")
    print("\n  By edge type:")
    for et, count in sorted(by_edge_type.items()):
        print(f"    {et}: {count}")

    if args.stats_only:
        return

    # Write output
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        for pair in pairs:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")

    print(f"\nWritten {total} training pairs to {args.output}")
    print(f"File size: {args.output.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
